# Site settings
title: KMAP Working Group
email: woochang_kang@korea.ac.kr
description: Korean Migration And Politics Working Group
baseurl: ""
url: "https://kmapgroup.github.io"

# Footer info
affiliation: >
  KMAP Working Group<br/>
  Korean Migration And Politics<br/>
  고려대학교 SSK 이민정치연구단<br/>
  Peace and Democracy Institute, Korea University

location: >
  Department of Political Science and International Relations<br/>
  Korea University<br/>
  145 Anam-ro, Seongbuk-gu, Seoul 02841, Korea

contact: >
  <a href="mailto:woochang_kang@korea.ac.kr"><i class="fa fa-envelope fa-1x"></i> woochang_kang@korea.ac.kr</a><br/>
  <a href="https://github.com/kmapgroup"><i class="fa fa-github fa-1x"></i> github.com/kmapgroup</a>

funding: >
  This work was supported by the National Research Foundation of Korea (NRF) under the Social Science Korea (SSK) program.

# Pages shown in navbar
nav_pages:
  - name: members
  - name: research
  - name: publications
  - name: events

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
